#include "npp.h"
#include <gtest/gtest.h>

TEST(ColorConversionMissingStubs, DISABLED_ReturnsNotImplemented) {
  EXPECT_EQ(nppiAlphaCompColorKey_8u_AC4R(nullptr, 0, 0, nullptr, 0, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NPPI_OP_ALPHA_OVER), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiAlphaCompColorKey_8u_AC4R_Ctx(nullptr, 0, 0, nullptr, 0, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NPPI_OP_ALPHA_OVER, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToCbYCr422_709HDTV_8u_AC4C2R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToCbYCr422_709HDTV_8u_AC4C2R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToCbYCr422_709HDTV_8u_C3C2R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToCbYCr422_709HDTV_8u_C3C2R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToCbYCr422_8u_AC4C2R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToCbYCr422_8u_AC4C2R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr420_709CSC_8u_AC4P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr420_709CSC_8u_AC4P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr420_709CSC_8u_C3P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr420_709CSC_8u_C3P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr420_709HDTV_8u_AC4P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr420_709HDTV_8u_AC4P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr420_JPEG_8u_C3P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr420_JPEG_8u_C3P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr420_JPEG_8u_P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr420_JPEG_8u_P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr422_8u_AC4P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr422_8u_AC4P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr422_JPEG_8u_C3P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr422_JPEG_8u_C3P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr422_JPEG_8u_P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr422_JPEG_8u_P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr444_JPEG_8u_C3P3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr444_JPEG_8u_C3P3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr444_JPEG_8u_P3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCbCr444_JPEG_8u_P3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCrCb420_709CSC_8u_AC4P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCrCb420_709CSC_8u_AC4P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCrCb420_709CSC_8u_C3P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCrCb420_709CSC_8u_C3P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCrCb420_8u_AC4P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCrCb420_8u_AC4P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCrCb420_8u_C3P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiBGRToYCrCb420_8u_C3P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCFAToRGBA_16u_C1AC4R(nullptr, 0, NppiSize{0, 0}, NppiRect{0, 0, 0, 0}, nullptr, 0, NPPI_BAYER_BGGR, NPPI_INTER_NN, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCFAToRGBA_16u_C1AC4R_Ctx(nullptr, 0, NppiSize{0, 0}, NppiRect{0, 0, 0, 0}, nullptr, 0, NPPI_BAYER_BGGR, NPPI_INTER_NN, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCFAToRGBA_8u_C1AC4R(nullptr, 0, NppiSize{0, 0}, NppiRect{0, 0, 0, 0}, nullptr, 0, NPPI_BAYER_BGGR, NPPI_INTER_NN, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCFAToRGBA_8u_C1AC4R_Ctx(nullptr, 0, NppiSize{0, 0}, NppiRect{0, 0, 0, 0}, nullptr, 0, NPPI_BAYER_BGGR, NPPI_INTER_NN, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCMYKOrYCCKToBGR_JPEG_8u_P4C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCMYKOrYCCKToBGR_JPEG_8u_P4C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCMYKOrYCCKToBGR_JPEG_8u_P4P3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCMYKOrYCCKToBGR_JPEG_8u_P4P3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCMYKOrYCCKToRGB_JPEG_8u_P4C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCMYKOrYCCKToRGB_JPEG_8u_P4C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCMYKOrYCCKToRGB_JPEG_8u_P4P3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCMYKOrYCCKToRGB_JPEG_8u_P4P3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToBGR_709HDTV_8u_C2C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToBGR_709HDTV_8u_C2C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToBGR_709HDTV_8u_C2C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToBGR_709HDTV_8u_C2C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToBGR_8u_C2C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToBGR_8u_C2C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToRGB_8u_C2C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToRGB_8u_C2C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToYCbCr411_8u_C2P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToYCbCr411_8u_C2P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToYCbCr420_8u_C2P2R(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToYCbCr420_8u_C2P2R_Ctx(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToYCbCr420_8u_C2P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToYCbCr420_8u_C2P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToYCbCr422_8u_C2P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToYCbCr422_8u_C2P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToYCbCr422_8u_C2R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToYCbCr422_8u_C2R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToYCrCb420_8u_C2P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCbYCr422ToYCrCb420_8u_C2P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32fC_16f_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32fC_16f_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32fC_16f_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32fC_16f_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32fC_8u_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32fC_8u_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32fC_8u_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32fC_8u_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C2IR(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C2IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C2R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C2R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_16f_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C2IR(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C2IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C2R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C2R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_IP3R(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_IP3R_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_P3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist32f_8s_P3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32fC_16f_C4IR(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32fC_16f_C4IR_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32fC_16f_C4R(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32fC_16f_C4R_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32fC_8u_C4IR(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32fC_8u_C4IR_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32fC_8u_C4R(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32fC_8u_C4R_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_16f_C1IR(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_16f_C1IR_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_16f_C1R(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_16f_C1R_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_16f_C3IR(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_16f_C3IR_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_16f_C3R(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_16f_C3R_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_16f_C4IR(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_16f_C4IR_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_16f_C4R(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_16f_C4R_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_AC4IR(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_AC4IR_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_AC4R(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_AC4R_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_C1IR(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_C1IR_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_C1R(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_C1R_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_C3IR(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_C3IR_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_C3R(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_C3R_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_C4IR(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_C4IR_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_C4R(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch32f_8u_C4R_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32fC_C4IR(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32fC_C4IR_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32fC_C4R(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32fC_C4R_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_AC4IR(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_AC4IR_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_AC4R(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_AC4R_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_C1IR(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_C1IR_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_C1R(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_C1R_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_C3IR(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_C3IR_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_C3R(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_C3R_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_C4IR(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_C4IR_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_C4R(0, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwistBatch_32f_C4R_Ctx(0, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32fC_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32fC_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32fC_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32fC_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C2IR(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C2IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C2R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C2R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_IP3R(nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_IP3R_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_P3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiColorTwist_32f_P3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCompColorKey_8u_C1R(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCompColorKey_8u_C1R_Ctx(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCompColorKey_8u_C3R(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCompColorKey_8u_C3R_Ctx(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCompColorKey_8u_C4R(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiCompColorKey_8u_C4R_Ctx(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiGammaFwd_8u_IP3R(nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiGammaFwd_8u_IP3R_Ctx(nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiGammaFwd_8u_P3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiGammaFwd_8u_P3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiGammaInv_8u_IP3R(nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiGammaInv_8u_IP3R_Ctx(nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiGammaInv_8u_P3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiGammaInv_8u_P3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPaletteSwap_16u_C3A0C4R(nullptr, 0, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPaletteSwap_16u_C3A0C4R_Ctx(nullptr, 0, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPaletteSwap_8u_C3A0C4R(nullptr, 0, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPaletteSwap_8u_C3A0C4R_Ctx(nullptr, 0, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_16u24u_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_16u24u_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_16u32u_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_16u32u_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_16u8u_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_16u8u_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_16u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_16u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_16u_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_16u_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_16u_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_16u_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_16u_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_16u_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_8u24u_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_8u24u_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_8u32u_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_8u32u_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_8u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_8u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_8u_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_8u_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_8u_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_8u_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_8u_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUTPalette_8u_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16s_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16u_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16u_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16u_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16u_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16u_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16u_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16u_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16u_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16u_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16u_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16u_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_16u_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_32f_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_8u_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_8u_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_8u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_8u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_8u_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_8u_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_8u_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_8u_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_8u_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_8u_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16s_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_16u_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_32f_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Cubic_8u_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16s_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_16u_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_C1R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_C1R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_32f_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_8u_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_8u_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_8u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_8u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_8u_C1IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_8u_C1IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_8u_C3IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_8u_C3IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_8u_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_8u_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_8u_C4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_8u_C4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_8u_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Linear_8u_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Trilinear_8u_AC4IR(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Trilinear_8u_AC4IR_Ctx(nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Trilinear_8u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Trilinear_8u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Trilinear_8u_C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUT_Trilinear_8u_C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, nullptr, nullptr, nullptr, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUVToRGB_8u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUVToRGB_8u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUVToRGB_8u_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiLUVToRGB_8u_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToCbYCr422Gamma_8u_C3C2R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToCbYCr422Gamma_8u_C3C2R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToCbYCr422_8u_C3C2R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToCbYCr422_8u_C3C2R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToLUV_8u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToLUV_8u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToLUV_8u_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToLUV_8u_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToXYZ_8u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToXYZ_8u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToXYZ_8u_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToXYZ_8u_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCC_8u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCC_8u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCC_8u_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCC_8u_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCbCr420_JPEG_8u_C3P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCbCr420_JPEG_8u_C3P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCbCr420_JPEG_8u_P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCbCr420_JPEG_8u_P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCbCr422_8u_P3C2R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCbCr422_8u_P3C2R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCbCr422_JPEG_8u_C3P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCbCr422_JPEG_8u_C3P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCbCr422_JPEG_8u_P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCbCr422_JPEG_8u_P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCbCr444_JPEG_8u_C3P3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCbCr444_JPEG_8u_C3P3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCbCr444_JPEG_8u_P3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCbCr444_JPEG_8u_P3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCrCb420_8u_AC4P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCrCb420_8u_AC4P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCrCb422_8u_C3C2R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCrCb422_8u_C3C2R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCrCb422_8u_P3C2R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiRGBToYCrCb422_8u_P3C2R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiXYZToRGB_8u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiXYZToRGB_8u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiXYZToRGB_8u_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiXYZToRGB_8u_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCCKToCMYK_JPEG_601_8u_P4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCCKToCMYK_JPEG_601_8u_P4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCCToRGB_8u_AC4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCCToRGB_8u_AC4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCCToRGB_8u_C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCCToRGB_8u_C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCbCr420_8u_P2P3R(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCbCr420_8u_P2P3R_Ctx(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCbCr420_8u_P3P2R(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCbCr420_8u_P3P2R_Ctx(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCbCr420_8u_P3R(nullptr, nullptr, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCbCr420_8u_P3R_Ctx(nullptr, nullptr, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCbCr422_8u_P2C2R(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCbCr422_8u_P2C2R_Ctx(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCbCr422_8u_P2P3R(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCbCr422_8u_P2P3R_Ctx(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCbCr422_8u_P3C2R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCbCr422_8u_P3C2R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCbCr422_8u_P3R(nullptr, nullptr, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCbCr422_8u_P3R_Ctx(nullptr, nullptr, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCrCb420_8u_P2P3R(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCrCb420_8u_P2P3R_Ctx(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCrCb422_8u_P3C2R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCrCb422_8u_P3C2R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCrCb422_8u_P3R(nullptr, nullptr, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411ToYCrCb422_8u_P3R_Ctx(nullptr, nullptr, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411_8u_P2P3R(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411_8u_P2P3R_Ctx(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411_8u_P3P2R(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr411_8u_P3P2R_Ctx(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGRBatch_8u_P3C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGRBatch_8u_P3C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGRBatch_8u_P3C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGRBatch_8u_P3C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGR_709CSC_8u_P3C3R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGR_709CSC_8u_P3C3R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGR_709HDTV_8u_P3C4R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGR_709HDTV_8u_P3C4R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGR_8u_P3C3R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGR_8u_P3C3R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGR_8u_P3C4R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGR_8u_P3C4R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGR_JPEG_8u_P3C3R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGR_JPEG_8u_P3C3R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGR_JPEG_8u_P3R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToBGR_JPEG_8u_P3R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToCbYCr422_8u_P2C2R(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToCbYCr422_8u_P2C2R_Ctx(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToRGBBatch_8u_P3C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToRGBBatch_8u_P3C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToRGBBatch_8u_P3C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToRGBBatch_8u_P3C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToRGB_JPEG_8u_P3C3R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToRGB_JPEG_8u_P3C3R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToRGB_JPEG_8u_P3R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToRGB_JPEG_8u_P3R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToYCbCr411_8u_P2P3R(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToYCbCr411_8u_P2P3R_Ctx(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToYCbCr411_8u_P3P2R(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToYCbCr411_8u_P3P2R_Ctx(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToYCbCr422_8u_P2C2R(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToYCbCr422_8u_P2C2R_Ctx(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToYCbCr422_8u_P2P3R(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToYCbCr422_8u_P2P3R_Ctx(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToYCbCr422_8u_P3R(nullptr, nullptr, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToYCbCr422_8u_P3R_Ctx(nullptr, nullptr, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToYCrCb420_8u_P2P3R(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420ToYCrCb420_8u_P2P3R_Ctx(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420_8u_P2P3R(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420_8u_P2P3R_Ctx(nullptr, 0, nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420_8u_P3P2R(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr420_8u_P3P2R_Ctx(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToBGRBatch_8u_P3C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToBGRBatch_8u_P3C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToBGRBatch_8u_P3C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToBGRBatch_8u_P3C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToBGR_JPEG_8u_P3C3R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToBGR_JPEG_8u_P3C3R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToBGR_JPEG_8u_P3R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToBGR_JPEG_8u_P3R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToCbYCr422_8u_C2R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToCbYCr422_8u_C2R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToRGBBatch_8u_P3C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToRGBBatch_8u_P3C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToRGBBatch_8u_P3C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToRGBBatch_8u_P3C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToRGB_8u_C2P3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToRGB_8u_C2P3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToRGB_JPEG_8u_P3C3R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToRGB_JPEG_8u_P3C3R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToRGB_JPEG_8u_P3R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToRGB_JPEG_8u_P3R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr411_8u_C2P2R(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr411_8u_C2P2R_Ctx(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr411_8u_C2P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr411_8u_C2P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr411_8u_P3P2R(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr411_8u_P3P2R_Ctx(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr411_8u_P3R(nullptr, nullptr, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr411_8u_P3R_Ctx(nullptr, nullptr, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr420_8u_C2P2R(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr420_8u_C2P2R_Ctx(nullptr, 0, nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr420_8u_C2P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr420_8u_C2P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr420_8u_P3P2R(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr420_8u_P3P2R_Ctx(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr420_8u_P3R(nullptr, nullptr, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCbCr420_8u_P3R_Ctx(nullptr, nullptr, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCrCb420_8u_C2P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCrCb420_8u_C2P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCrCb422_8u_C2R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCrCb422_8u_C2R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCrCb422_8u_P3C2R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422ToYCrCb422_8u_P3C2R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422_8u_C2P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422_8u_C2P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422_8u_P3C2R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr422_8u_P3C2R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr444ToBGR_JPEG_8u_P3C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr444ToBGR_JPEG_8u_P3C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr444ToBGR_JPEG_8u_P3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr444ToBGR_JPEG_8u_P3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr444ToRGB_JPEG_8u_P3C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr444ToRGB_JPEG_8u_P3C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr444ToRGB_JPEG_8u_P3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCr444ToRGB_JPEG_8u_P3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToBGRBatch_8u_C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToBGRBatch_8u_C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToBGRBatch_8u_C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToBGRBatch_8u_C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToBGRBatch_8u_P3C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToBGRBatch_8u_P3C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToBGRBatch_8u_P3C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToBGRBatch_8u_P3C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToBGR_709CSC_8u_P3C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToBGR_709CSC_8u_P3C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToBGR_709CSC_8u_P3C4R(nullptr, 0, nullptr, 0, NppiSize{0, 0}, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToBGR_709CSC_8u_P3C4R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToRGBBatch_8u_C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToRGBBatch_8u_C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToRGBBatch_8u_C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToRGBBatch_8u_C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToRGBBatch_8u_P3C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToRGBBatch_8u_P3C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToRGBBatch_8u_P3C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCbCrToRGBBatch_8u_P3C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb420ToCbYCr422_8u_P3C2R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb420ToCbYCr422_8u_P3C2R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb420ToRGB_8u_P3C4R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, 0), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb420ToRGB_8u_P3C4R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, 0, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb420ToYCbCr411_8u_P3P2R(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb420ToYCbCr411_8u_P3P2R_Ctx(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb420ToYCbCr420_8u_P3P2R(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb420ToYCbCr420_8u_P3P2R_Ctx(nullptr, nullptr, nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb420ToYCbCr422_8u_P3C2R(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb420ToYCbCr422_8u_P3C2R_Ctx(nullptr, nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb420ToYCbCr422_8u_P3R(nullptr, nullptr, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb420ToYCbCr422_8u_P3R_Ctx(nullptr, nullptr, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb422ToRGB_8u_C2C3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb422ToRGB_8u_C2C3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb422ToRGB_8u_C2P3R(nullptr, 0, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb422ToRGB_8u_C2P3R_Ctx(nullptr, 0, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb422ToYCbCr411_8u_C2P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb422ToYCbCr411_8u_C2P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb422ToYCbCr420_8u_C2P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb422ToYCbCr420_8u_C2P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb422ToYCbCr422_8u_C2P3R(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYCrCb422ToYCbCr422_8u_C2P3R_Ctx(nullptr, 0, nullptr, nullptr, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV420ToBGRBatch_8u_P3C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV420ToBGRBatch_8u_P3C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV420ToBGRBatch_8u_P3C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV420ToBGRBatch_8u_P3C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV420ToRGBBatch_8u_P3C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV420ToRGBBatch_8u_P3C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV420ToRGBBatch_8u_P3C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV420ToRGBBatch_8u_P3C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV422ToBGRBatch_8u_P3C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV422ToBGRBatch_8u_P3C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV422ToBGRBatch_8u_P3C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV422ToBGRBatch_8u_P3C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV422ToRGBBatch_8u_P3C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV422ToRGBBatch_8u_P3C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV422ToRGBBatch_8u_P3C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUV422ToRGBBatch_8u_P3C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToBGRBatch_8u_C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToBGRBatch_8u_C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToBGRBatch_8u_C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToBGRBatch_8u_C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToBGRBatch_8u_P3C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToBGRBatch_8u_P3C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToBGRBatch_8u_P3C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToBGRBatch_8u_P3C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToRGBBatch_8u_C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToRGBBatch_8u_C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToRGBBatch_8u_C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToRGBBatch_8u_C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToRGBBatch_8u_P3C3R(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToRGBBatch_8u_P3C3R_Advanced(nullptr, nullptr, 0, NppiSize{0, 0}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToRGBBatch_8u_P3C3R_Advanced_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
  EXPECT_EQ(nppiYUVToRGBBatch_8u_P3C3R_Ctx(nullptr, nullptr, 0, NppiSize{0, 0}, NppStreamContext{}), NPP_NOT_IMPLEMENTED_ERROR);
}
